### ISSUE TITLE
[1주차 실습] 컴포즈 소개 및 기본 레이아웃 함수 빌드해보기

### ISSUE THREAD

**Issue by b1urrrr** [not-compose-coffee/chaeyeon-jeon#1]
# TO-DO LIST
### 컴포즈 프로젝트 생성
- [x] 배경 색상 변경하기
- [x] 패딩 추가하기
### 기본 레이아웃 함수 및 빌드해보기
- [x] 새 컴저블 함수 추가
- [x] 글꼴 크기 변경
- [x] 다른 텍스트 요소 추가
- [x] 하나의 행에 텍스트 요소 정렬
### 이미지 및 속성 추가
- [x] 이미지 추가
    - [x] Box 레이아웃 추가
- [x] 이미지 컴포저블 확장
    - [x] 콘텐츠 조정
    - [x] 텍스트 정렬
    - [x] 패딩 추가
### 버튼 추가 [🔗](https://github.com/not-compose-coffee/chaeyeon-jeon/blob/develop/week1/practice/DiceRoller/app/src/main/java/com/example/diceroller/MainActivity.kt)
- [x] 레이아웃 인프라 만들기
- [x] 수정자 추가
- [x] 세로 레이아웃 만들기
- [x] 버튼 추가
- [x] 이미지 추가
- [x] Image 컴포저블 추가
- [x] ⭐ 주사위 굴리기 로직 빌드
    - [x] Button을 대화형으로 만들기
    - [x] 조건문 추가
<br>

```
1주차 제출 : ~ 23.04.23. (일)
```
