### ISSUE TITLE
[2주차 실습] 컴포즈의 상태

### ISSUE THREAD

**Issue by b1urrrr** [not-compose-coffee/chaeyeon-jeon#5]
# TO-DO LIST
### 팁 계산기 만들기
- [ ] 초기 설정
- [ ] 화면 제목 표시
- [ ] TextField 컴포저블 추가
### Compose에서 상태 사용
- [ ] 컴포지션
- [ ] Remember 함수를 사용하여 상태 저장
- [ ] 상태 및 리컴포지션의 작동 방식
- [ ] 디자인 수정
    - [ ] 텍스트 상자에 라벨 추가
    - [ ] 팁 금액 계산
    - [ ] calculateTip() 함수 사용
    - [ ] 계산된 팁 금액 표시
### 상태 호이스팅
- [ ] Stateful과 Stateless 컴포저블 비교
### 대화형 팁 계산기 만들기
- [ ] 초기 세팅
- [ ] 팁 비율 텍스트 필드 추가
### 키보드 버튼 및 작업 설정
- [ ] 키보드 버튼 설정
- [ ] 키보드 작업 설정
- [ ] 스위치 추가
    - [ ] calculateTip() 함수를 업데이트하여 팁 반올림하기
<br>

```
2주차 제출 : ~ 23.04.30. (일)
그치만 난 나만의 속도로 간다.....🐌...
```
